#!/bin/sh

# See: https://www.kernel.org/doc/html/v6.12/usb/gadget_configfs.html

setup_gadget() {
    BCD_USB="0x0200"        # USB 2.0
    ID_VENDOR="0x1d6b"      # Linux Foundation
    ID_PRODUCT="0x0104"     # Multifunction Composite Gadget
    # BCD_DEVICE="0x0612"   # 6.12

    STR_SERIALNUMBER=$(cat /proc/device-tree/serial-number)
    STR_MANUFACTURER="BeagleBoard.org"
    STR_PRODUCT=$(sed "s/ /_/g" /proc/device-tree/model | tr -d '\000')

    if [ ! -f /storage.img ]; then
        echo "gadget: /storage.img does not exist!"
        exit 1
    fi

    mount -t configfs none /sys/kernel/config || exit
    mkdir /sys/kernel/config/usb_gadget/storage || exit
    cd /sys/kernel/config/usb_gadget/storage || exit

    echo "$BCD_USB" > bcdUSB
    echo "$ID_VENDOR" > idVendor
    echo "$ID_PRODUCT" > idProduct
    # echo "$BCD_DEVICE" > bcdDevice

    # Directory for English language
    mkdir strings/0x409
    echo "$STR_SERIALNUMBER" > strings/0x409/serialnumber
    echo "$STR_MANUFACTURER" > strings/0x409/manufacturer
    echo "$STR_PRODUCT" > strings/0x409/product

    mkdir configs/storage.1
    mkdir configs/storage.1/strings/0x409
    echo "BeagleBone Composite" > configs/storage.1/strings/0x409/configuration
    echo 500 > configs/storage.1/MaxPower

    mkdir functions/mass_storage.usb0
    echo 1 > functions/mass_storage.usb0/lun.0/nofua
    echo /storage.img > functions/mass_storage.usb0/lun.0/file
    echo 0 > functions/mass_storage.usb0/lun.0/removable

    ln -s functions/mass_storage.usb0 configs/storage.1

    echo musb-hdrc.0 > UDC
}

start() {
    if mount | grep -q /storage; then
        umount /storage
    fi
    setup_gadget
}

stop() {
    cd /sys/kernel/config/usb_gadget/storage || exit 0

    echo > UDC
}

case "$1" in
    start)
        # Normally only ran when a button is pressed during boot
        is-any-button-pressed && start
        ;;
    force-start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|force-start|stop|restart}"
        exit 1
esac
